<a href="https://colab.research.google.com/github/Jullian29t/programacion1/blob/main/Quiz_C%C3%B3digos_Clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Escritura de archivos desde python

In [11]:
with open("archivo.txt", "w") as f:
  f.write("Hola este es un archivo de texto. \n")
  f.write("segunda linea")

In [12]:
with open("archivo.txt", "r") as f:
    print(f.read())

Hola este es un archivo de texto.
segunda linea

con el argumento "r" se leen archivos

In [23]:
from google.colab import files
files.download("archivo.txt")

In [24]:
with open("archivo.txt", "a") as f:
  f.write("\nEsta es una nueva linea añadida.")

In [27]:
with open("archivo.txt", "r") as f:
    print(f.read())

Hola este es un archivo de texto.
segunda lineatercera lineaEsta es una nueva linea añadida.
 Esta es una nueva linea añadida.
Esta es una nueva linea añadida.
Esta es una nueva linea añadida.

In [28]:
from google.colab import files
files.download("archivo.txt")

In [30]:
from google.colab import files
uploaded = files.upload()

Saving archivo.txt to archivo (2).txt

In [33]:
with open("archivo.txt (2)", "w") as f:
    f.write("Este archivo fue completamente modificado\n")
    f.write("Nueva linea 1\n")
    f.write("Nueva linea 2\n")

In [34]:
with open("archivo.txt (2)", "r") as f:
    print(f.read())

Este archivo fue completamente modificado
Nueva linea 1
Nueva linea 2

In [36]:
from google.colab import files
files.download("archivo.txt (2)")

Con archivos .csv

In [38]:
import csv
datos = [
    ["Nnombre", "Edad", "Ciudad"],
    ["Ana", 25, "Bogota"],
    ["Juan", 30, "Medellin"],
    ["Maria", 28, "Cali"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

In [42]:
with open("datos.csv", "r") as f:
    print(f.read())

Nnombre,Edad,Ciudad
Ana,25,Bogota
Juan,30,Medellin
Maria,28,Cali

In [43]:
files.download("datos.csv")

In [44]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [46]:
ruta = "/content/drive/MyDrive/datos.csv"
import shutil
shutil.copy("datos.csv", ruta)

'/content/drive/MyDrive/datos.csv'

In [47]:
with open(ruta, "r") as f:
    print(f.read())

Nnombre,Edad,Ciudad
Ana,25,Bogota
Juan,30,Medellin
Maria,28,Cali

In [50]:
with open(ruta, "r") as f:
    data = list(csv.reader(f))

data.append(["Diego", "28", "Armenia"])
data

[['Nnombre', 'Edad', 'Ciudad'],
 ['Ana', '25', 'Bogota'],
 ['Juan', '30', 'Medellin'],
 ['Maria', '28', 'Cali'],
 ['Diego', '28', 'Armenia']]

In [52]:
import pandas as pd
data1 = pd.DataFrame(data)
data1

         0     1         2
0  Nnombre  Edad    Ciudad
1      Ana    25    Bogota
2     Juan    30  Medellin
3    Maria    28      Cali
4    Diego    28   Armenia

In [53]:
import csv

ruta = "/content/drive/MyDrive/datos.csv"

# Leer
with open(ruta, "r") as f:
    data = list(csv.reader(f))

# Mostrar antes
print("ANTES:")
print(data)

# Agregar fila
data.append(["Diego", "28", "Armenia"])

# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

ANTES:
[['Nnombre', 'Edad', 'Ciudad'], ['Ana', '25', 'Bogota'], ['Juan', '30', 'Medellin'], ['Maria', '28', 'Cali']]

DESPUÉS:
Nnombre,Edad,Ciudad
Ana,25,Bogota
Juan,30,Medellin
Maria,28,Cali
Diego,28,Armenia

In [54]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'minecraft',
 'Planteamiento del problema (1).docx',
 'Planteamiento del problema (1).gdoc',
 'Planteamiento del problema.docx',
 'Planteamiento del problema.gdoc',
 'Documento sin título.pdf',
 'Documento sin título.gdoc',
 '20250916_072444.jpg',
 '20250916_122247.jpg',
 'Screenshot_20250916_122324_Chrome.jpg',
 'Screenshot_20250924_123713_Chrome.jpg',
 'Screenshot_20250924_123726_Chrome (2).jpg',
 'Screenshot_20250924_123726_Chrome (1).jpg',
 'Screenshot_20250924_123726_Chrome.jpg',
 '17588277432121706159807294250937.jpg',
 'PDF RESULTADOS AC202530058461_copia.pdf',
 'Google AI Studio',
 'PDG 2025 - CIELO RASO - AULA C3-2 - EMILSE QUITIÁN 14-10-25.docx',
 'Presentación proyecto aula C3-2.pptx',
 'requisitos_afiliacion_1_copia.pdf',
 'TI Julian Usma.pdf',
 'Untitled0.ipynb',
 'datos.csv']

In [56]:
import pandas as pd
df = pd.read_csv(ruta)
df

  Nnombre  Edad    Ciudad
0     Ana    25    Bogota
1    Juan    30  Medellin
2   Maria    28      Cali
3   Diego    28   Armenia

In [57]:
df["Nueva_columna"] = "valor"
df["Nueva_columna"] = [10,20,30,None]
df

  Nnombre  Edad    Ciudad  Nueva_columna
0     Ana    25    Bogota           10.0
1    Juan    30  Medellin           20.0
2   Maria    28      Cali           30.0
3   Diego    28   Armenia            NaN